[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_vault = "GngcpYJB9cGCs2ffwNSJyiGHvyRpAmf7dk978JGPm57D"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "http://localhost:8899"
wallet = "~/my-solana-wallet/my-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
